import { execSync } from "child_process"
import * as fs from "fs"
import * as path from "path"
import type { FastifyInstance } from "fastify"
import { z } from "zod"

const WORKSPACE_ROOT = process.env.CLI_WORKSPACE_ROOT || process.cwd()
const VERCEL_DEPLOY_HOOK_URL = process.env.VERCEL_DEPLOY_HOOK_URL
const VERCEL_TOKEN = process.env.VERCEL_TOKEN
const VERCEL_PROJECT_ID = process.env.VERCEL_PROJECT_ID
const VERCEL_TEAM_ID = process.env.VERCEL_TEAM_ID
const STARGUARD_BASE = process.env.STARGUARD_BASE_URL || "https://starguard.vercel.app"

// Cache for workflow definitions fetched from StarGuard
let workflowDefinitionsCache: any = null
let workflowCacheTime = 0
const WORKFLOW_CACHE_TTL = 300_000 // 5 minutes

interface TokiDAPPWebSocket {
  send: (msg: string) => void
  close: (code?: number, reason?: string) => void
}

const activeSockets = new Map<string, TokiDAPPWebSocket>()

// ── Tool Implementations ─────────────────────────────────────

async function investigateCodebase(query: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Searching the codebase..." }))

  const keywords = query.replace(/investigate|find|search|look|show|read|examine/gi, "").trim().split(/\s+/).filter(Boolean)
  if (keywords.length === 0) return "What would you like me to investigate?"

  try {
    const pattern = keywords.join("|")
    let results: string
    try {
      results = execSync(
        `rg -l -i "${pattern}" --type ts --type tsx --type css --glob '!node_modules' --glob '!.next' --glob '!public/codenomad' 2>/dev/null | head -20`,
        { cwd: WORKSPACE_ROOT, encoding: "utf-8", maxBuffer: 1024 * 1024 },
      )
    } catch {
      results = ""
    }

    const fileList = results.trim().split("\n").filter(Boolean)
    if (fileList.length === 0) return `No files found matching: ${keywords.join(", ")}`

    const previews: string[] = []
    for (const file of fileList.slice(0, 3)) {
      try {
        const content = execSync(`head -30 "${file}"`, { cwd: WORKSPACE_ROOT, encoding: "utf-8", maxBuffer: 1024 * 1024 })
        previews.push(`📄 ${file}:\n${content}`)
      } catch {
        previews.push(`📄 ${file}: (could not read)`)
      }
    }

    return [
      `Found ${fileList.length} files matching: ${keywords.join(", ")}`,
      "",
      ...fileList.map((f) => `- ${f}`),
      "",
      "--- Previews ---",
      "",
      ...previews,
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

async function generateFeature(prompt: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Generating feature..." }))

  const filesCreated: string[] = []

  try {
    if (/page|route/i.test(prompt)) {
      const match = prompt.match(/(\w+)\s*page/i) || prompt.match(/add\s+(?:a\s+)?(\w+)/i)
      const pageName = match ? match[1].toLowerCase() : "new-feature"
      const dir = path.join(WORKSPACE_ROOT, "src", "app", pageName)
      fs.mkdirSync(dir, { recursive: true })

      const pageContent = [
        "'use client'",
        "",
        `export default function ${pageName.charAt(0).toUpperCase() + pageName.slice(1)}Page() {`,
        "  return (",
        `    <div className="p-8">`,
        `      <h1 className="text-2xl font-bold text-white">${pageName.charAt(0).toUpperCase() + pageName.slice(1)}</h1>`,
        `      <p className="text-gray-400 mt-2">Generated by TokiDAPP Concierge</p>`,
        "    </div>",
        "  )",
        "}",
        "",
      ].join("\n")

      fs.writeFileSync(path.join(dir, "page.tsx"), pageContent)
      filesCreated.push(`src/app/${pageName}/page.tsx`)
    }

    if (/component/i.test(prompt)) {
      const match = prompt.match(/(\w+)\s*component/i) || prompt.match(/component\s+(\w+)/i)
      const compName = match ? match[1] : "GeneratedComponent"
      const compPascal = compName.charAt(0).toUpperCase() + compName.slice(1)

      const componentContent = [
        "'use client'",
        "",
        `export function ${compPascal}({ className = "" }: { className?: string }) {`,
        "  return (",
        `    <div className={\`p-4 rounded-xl border border-white/10 bg-white/5 \${className}\`}>`,
        `      <p className="text-gray-400">${compPascal}</p>`,
        "    </div>",
        "  )",
        "}",
        "",
      ].join("\n")

      const compDir = path.join(WORKSPACE_ROOT, "src", "components")
      fs.mkdirSync(compDir, { recursive: true })
      fs.writeFileSync(path.join(compDir, `${compPascal}.tsx`), componentContent)
      filesCreated.push(`src/components/${compPascal}.tsx`)
    }

    if (filesCreated.length === 0) {
      return "Please be more specific. Try: 'Add a metrics page' or 'Create a Dashboard component'"
    }

    return [
      `Created ${filesCreated.length} file(s):`,
      "",
      ...filesCreated.map((f) => `- ${f}`),
      "",
      "Run `bun run type-check` to verify.",
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

async function runTests(send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Running tests..." }))

  try {
    const startTime = Date.now()
    let output: string
    try {
      output = execSync("bun run test 2>&1", { cwd: WORKSPACE_ROOT, encoding: "utf-8", maxBuffer: 1024 * 1024, timeout: 120000 })
    } catch (e: any) {
      output = e.stdout || e.message || "Test execution failed"
    }

    const duration = ((Date.now() - startTime) / 1000).toFixed(1)
    const passMatch = output.match(/(\d+)\s+passed/i)
    const failMatch = output.match(/(\d+)\s+failed/i)
    const passed = passMatch ? passMatch[1] : "?"
    const failed = failMatch ? failMatch[1] : "0"

    return [
      `Tests completed in ${duration}s`,
      `Passed: ${passed} | Failed: ${failed}`,
      failed !== "0" ? "Some tests failed." : "All tests passing!",
      "",
      "--- Last 20 lines ---",
      output.split("\n").slice(-20).join("\n"),
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

async function gitStatus(): Promise<string> {
  try {
    const branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd: WORKSPACE_ROOT, encoding: "utf-8" }).trim()
    const status = execSync("git status --short", { cwd: WORKSPACE_ROOT, encoding: "utf-8" }).trim()
    const log = execSync("git log --oneline -5", { cwd: WORKSPACE_ROOT, encoding: "utf-8" }).trim()
    const filesChanged = status ? status.split("\n").length : 0

    return [
      `Branch: ${branch}`,
      `Uncommitted: ${filesChanged} file(s)`,
      status ? `\n${status}` : "\n   (clean)",
      "",
      "--- Recent commits ---",
      log,
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

async function gitCommitPush(commitMsg: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Committing changes..." }))

  try {
    const branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd: WORKSPACE_ROOT, encoding: "utf-8" }).trim()
    execSync("git add -A", { cwd: WORKSPACE_ROOT, encoding: "utf-8" })
    execSync(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`, { cwd: WORKSPACE_ROOT, encoding: "utf-8" })

    send(JSON.stringify({ type: "stream", delta: "Pushing to remote..." }))
    execSync(`git push origin ${branch}`, { cwd: WORKSPACE_ROOT, encoding: "utf-8", timeout: 30000 })

    const hash = execSync("git rev-parse HEAD", { cwd: WORKSPACE_ROOT, encoding: "utf-8" }).trim()
    return `Committed and pushed: ${hash.slice(0, 7)} on ${branch}`
  } catch (err) {
    return `Git error: ${(err as Error).message}`
  }
}

async function triggerVercelDeploy(send: (msg: string) => void): Promise<string> {
  if (!VERCEL_DEPLOY_HOOK_URL) {
    return "VERCEL_DEPLOY_HOOK_URL not configured. Set it in the environment."
  }

  send(JSON.stringify({ type: "stream", delta: "Triggering Vercel deploy..." }))

  try {
    const res = await fetch(VERCEL_DEPLOY_HOOK_URL, { method: "POST" })
    if (!res.ok) {
      const err = await res.text()
      return `Deploy hook failed: ${res.status} ${err}`
    }
    return "Deploy triggered on Vercel. Building..."
  } catch (err) {
    return `Deploy error: ${(err as Error).message}`
  }
}

async function checkDeployStatus(): Promise<string> {
  if (!VERCEL_TOKEN) return "VERCEL_TOKEN not configured."

  try {
    const params = new URLSearchParams({ limit: "1" })
    if (VERCEL_PROJECT_ID) params.set("projectId", VERCEL_PROJECT_ID)
    if (VERCEL_TEAM_ID) params.set("teamId", VERCEL_TEAM_ID)

    const res = await fetch(`https://api.vercel.com/v6/deployments?${params}`, {
      headers: { Authorization: `Bearer ${VERCEL_TOKEN}` },
    })

    if (!res.ok) return "Could not fetch deploy status."
    const data: any = await res.json()
    const deploy = data.deployments?.[0]
    if (!deploy) return "No deployments found."

    return [
      `Latest deploy: ${deploy.name}`,
      `URL: https://${deploy.url}`,
      `State: ${deploy.readyState}`,
      `Created: ${new Date(deploy.createdAt).toISOString()}`,
    ].join("\n")
  } catch {
    return "Could not fetch deploy status."
  }
}

// ── Agent Spawning ────────────────────────────────────────────

async function spawnAgent(prompt: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Spawning agent workspace..." }))

  if (!STARGUARD_BASE) return "StarGuard API not configured."

  // Parse agent type from prompt
  const agentType = prompt.includes("opencoder")
    ? "OPENCODER"
    : prompt.includes("openagent")
      ? "OPENAGENT"
      : prompt.includes("buildmate")
        ? "BUILDMATE"
        : "OPENCODE"

  const match = prompt.match(/in\s+([\w/-]+)/i)
  const workspacePath = match ? path.join(WORKSPACE_ROOT, match[1]) : WORKSPACE_ROOT

  try {
    const res = await fetch(`${STARGUARD_BASE}/api/tokidapp/agents/spawn`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId: `codenomad_${Date.now()}`,
        workspacePath,
        agentType,
        workspaceName: `Agent-${agentType}-${Date.now()}`,
      }),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to spawn agent: ${err}`
    }

    const workspace = await res.json()
    return [
      `✅ **${agentType} agent spawned!**`,
      ``,
      `Workspace ID: \`${workspace.codenomadWorkspaceId || workspace.id}\``,
      workspace.codenomadProxyUrl ? `Proxy URL: ${workspace.codenomadProxyUrl}` : "",
      `Status: ${workspace.status}`,
      ``,
      `The agent is ready. Assign tasks to it using "assign task to <agent>".`,
    ].filter(Boolean).join("\n")
  } catch (err) {
    return `Error spawning agent: ${(err as Error).message}`
  }
}

// ── Task Scheduling ───────────────────────────────────────────

async function scheduleTask(prompt: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Creating scheduled task..." }))

  if (!STARGUARD_BASE) return "StarGuard API not configured."

  // Parse task info from prompt
  const titleMatch = prompt.match(/(?:task|to)\s+[""]?([^""]+?)[""]?\s*(?:for|at|with|$)/i)
  const title = titleMatch ? titleMatch[1].trim() : prompt.replace(/schedule|create|add|task/gi, "").trim()
  const priorityMatch = prompt.match(/priority\s*[:\s]*(\d+)/i)
  const priority = priorityMatch ? parseInt(priorityMatch[1]) : 0

  // Parse scheduled time
  let scheduledFor: string | undefined
  const timeMatch = prompt.match(/(?:at|for)\s+(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})/i) || prompt.match(/(?:at|for)\s+(\d{4}-\d{2}-\d{2})/i)
  if (timeMatch) scheduledFor = timeMatch[1]

  // Parse agent type
  const agentType = prompt.includes("opencoder")
    ? "OPENCODER" : prompt.includes("openagent")
      ? "OPENAGENT" : "OPENCODE"

  // Parse assignee
  const assignMatch = prompt.match(/(?:assign|to|for)\s+user\s+(\S+@\S+)/i)
  const assignedToUserId = assignMatch ? assignMatch[1] : undefined

  try {
    const body: Record<string, unknown> = {
      sessionId: `codenomad_${Date.now()}`,
      title,
      agentType,
      priority,
    }
    if (scheduledFor) body.scheduledFor = scheduledFor
    if (assignedToUserId) body.assignedToUserId = assignedToUserId

    const res = await fetch(`${STARGUARD_BASE}/api/tokidapp/tasks`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to schedule task: ${err}`
    }

    const task = await res.json()
    return [
      `✅ **Task scheduled!**`,
      ``,
      `Title: ${task.title}`,
      `ID: \`${task.id}\``,
      `Agent: ${task.agentType}`,
      `Priority: ${task.priority}`,
      scheduledFor ? `Scheduled: ${scheduledFor}` : "Status: PENDING (no schedule set)",
      assignedToUserId ? `Assigned to: ${assignedToUserId}` : "",
      ``,
      `Use "list tasks" to see all scheduled tasks.`,
    ].filter(Boolean).join("\n")
  } catch (err) {
    return `Error scheduling task: ${(err as Error).message}`
  }
}

async function listTasks(filter: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Fetching tasks..." }))

  if (!STARGUARD_BASE) return "StarGuard API not configured."

  try {
    const params = new URLSearchParams()
    if (filter.includes("pending")) params.set("status", "PENDING")
    else if (filter.includes("assigned")) params.set("status", "ASSIGNED")
    else if (filter.includes("in progress")) params.set("status", "IN_PROGRESS")
    else if (filter.includes("complete")) params.set("status", "COMPLETED")

    const res = await fetch(`${STARGUARD_BASE}/api/tokidapp/tasks?${params}`, {
      headers: { "Content-Type": "application/json" },
    })

    if (!res.ok) return "Could not fetch tasks."
    const tasks: any[] = await res.json()

    if (tasks.length === 0) return "No tasks found."

    return [
      `📋 **${tasks.length} task(s)**`,
      "",
      ...tasks.map((t, i) =>
        `**${i + 1}. ${t.title}**` +
        `\n   Status: ${t.status} | Agent: ${t.agentType} | Priority: ${t.priority}` +
        (t.assignedToUserId ? `\n   Assigned to: \`${t.assignedToUserId}\`` : "") +
        (t.scheduledFor ? `\n   Scheduled: ${new Date(t.scheduledFor).toISOString()}` : "") +
        (t.resultSummary ? `\n   Result: ${t.resultSummary}` : ""),
      ),
    ].join("\n")
  } catch (err) {
    return `Error listing tasks: ${(err as Error).message}`
  }
}

async function assignTask(prompt: string, send: (msg: string) => void): Promise<string> {
  send(JSON.stringify({ type: "stream", delta: "Assigning task..." }))

  if (!STARGUARD_BASE) return "StarGuard API not configured."

  // Parse task ID and assignee
  const taskIdMatch = prompt.match(/task\s+(\S+)/i)
  const userMatch = prompt.match(/(?:to|user)\s+(\S+@\S+|\S+)/i)

  if (!taskIdMatch) return "Please specify a task ID. Example: assign task abc123 to user@example.com"
  if (!userMatch) return "Please specify a user. Example: assign task abc123 to user@example.com"

  const taskId = taskIdMatch[1]
  const assignee = userMatch[1]

  try {
    const res = await fetch(`${STARGUARD_BASE}/api/tokidapp/tasks/${taskId}/assign`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ assignedToUserId: assignee }),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to assign task: ${err}`
    }

    const task = await res.json()
    return [
      `✅ **Task assigned!**`,
      ``,
      `Task: ${task.title}`,
      `Assigned to: ${assignee}`,
      `Status: ${task.status}`,
    ].join("\n")
  } catch (err) {
    return `Error assigning task: ${(err as Error).message}`
  }
}

// ── Message Router ────────────────────────────────────────────

async function routeMessage(
  content: string,
  send: (msg: string) => void,
  workflowSlug?: string,
  workflowStep?: number,
): Promise<void> {
  // If workflow context is provided, route by workflow slug
  if (workflowSlug && workflowStep) {
    const slugToHint: Record<string, string> = {
      "investigate-code": "investigate",
      "generate-feature": "generate",
      "run-tests": "test",
      "deploy-app": "deploy",
      "spawn-agent": "spawn agent",
      "schedule-task": "schedule task",
      "assign-task": "assign task",
    }
    const hint = slugToHint[workflowSlug]
    if (hint) {
      content = hint + " " + content
    }
  }
  const lower = content.toLowerCase()

  if (lower.includes("investigate") || lower.includes("find") || lower.includes("search") || lower.includes("look")) {
    send(JSON.stringify({ type: "tool_call", id: "1", tool: "investigate_codebase", status: "running", summary: "Searching codebase..." }))
    const result = await investigateCodebase(content, send)
    send(JSON.stringify({ type: "tool_result", id: "1", tool: "investigate_codebase", status: "complete", summary: result }))
  } else if (lower.includes("generate") || lower.includes("create") || lower.includes("add") || lower.includes("make")) {
    send(JSON.stringify({ type: "tool_call", id: "2", tool: "generate_feature", status: "running", summary: "Generating feature..." }))
    const result = await generateFeature(content, send)
    send(JSON.stringify({ type: "tool_result", id: "2", tool: "generate_feature", status: "complete", summary: result }))
  } else if (lower.includes("test") || lower.includes("verify") || lower.includes("check")) {
    send(JSON.stringify({ type: "tool_call", id: "3", tool: "run_tests", status: "running", summary: "Running tests..." }))
    const result = await runTests(send)
    send(JSON.stringify({ type: "tool_result", id: "3", tool: "run_tests", status: "complete", summary: result }))
  } else if (lower.includes("git status") || lower.includes("branch") || lower.includes("repo")) {
    send(JSON.stringify({ type: "tool_call", id: "4", tool: "git_status", status: "running", summary: "Checking git state..." }))
    const result = await gitStatus()
    send(JSON.stringify({ type: "tool_result", id: "4", tool: "git_status", status: "complete", summary: result }))
  } else if (lower.includes("deploy") || lower.includes("release") || lower.includes("publish")) {
    send(JSON.stringify({ type: "tool_call", id: "5", tool: "git_commit_push", status: "running", summary: "Committing and pushing..." }))
    const gitResult = await gitCommitPush(content, send)
    send(JSON.stringify({ type: "tool_result", id: "5", tool: "git_commit_push", status: "complete", summary: gitResult }))

    send(JSON.stringify({ type: "tool_call", id: "6", tool: "trigger_deploy", status: "running", summary: "Triggering Vercel deploy..." }))
    const deployResult = await triggerVercelDeploy(send)
    send(JSON.stringify({ type: "tool_result", id: "6", tool: "trigger_deploy", status: "complete", summary: deployResult }))
  } else if (lower.includes("spawn") || lower.includes("start agent") || lower.includes("launch agent")) {
    send(JSON.stringify({ type: "tool_call", id: "7", tool: "spawn_agent", status: "running", summary: "Spawning agent..." }))
    const result = await spawnAgent(content, send)
    send(JSON.stringify({ type: "tool_result", id: "7", tool: "spawn_agent", status: "complete", summary: result }))
  } else if (lower.includes("schedule") || lower.includes("create task") || (lower.includes("add task") && !lower.includes("add a page"))) {
    send(JSON.stringify({ type: "tool_call", id: "8", tool: "schedule_task", status: "running", summary: "Scheduling task..." }))
    const result = await scheduleTask(content, send)
    send(JSON.stringify({ type: "tool_result", id: "8", tool: "schedule_task", status: "complete", summary: result }))
  } else if (lower.includes("list task") || lower.includes("show task") || lower.includes("my tasks") || lower.includes("all tasks")) {
    send(JSON.stringify({ type: "tool_call", id: "9", tool: "list_tasks", status: "running", summary: "Fetching tasks..." }))
    const result = await listTasks(content, send)
    send(JSON.stringify({ type: "tool_result", id: "9", tool: "list_tasks", status: "complete", summary: result }))
  } else if (lower.includes("assign task") || lower.includes("assign to")) {
    send(JSON.stringify({ type: "tool_call", id: "10", tool: "assign_task", status: "running", summary: "Assigning task..." }))
    const result = await assignTask(content, send)
    send(JSON.stringify({ type: "tool_result", id: "10", tool: "assign_task", status: "complete", summary: result }))
  } else {
    send(JSON.stringify({
      type: "message",
      content: `I can help with:
• **Investigate** — search and read codebase files
• **Generate** — create new pages, components, routes
• **Test** — run the test suite
• **Git status** — check branch, changes, history
• **Deploy** — commit, push, and deploy to Vercel
• **Spawn agent** — launch OpenCode/OpenCoder/OpenAgent workspaces
• **Schedule task** — create and schedule tasks for agents or users
• **List tasks** — view all pending/assigned/completed tasks
• **Assign task** — assign a task to a specific user

What would you like to do?`,
    }))
  }
}

// ── Workflow Definitions (fetched from StarGuard) ──────────────

async function fetchWorkflowDefinitions(): Promise<any[]> {
  try {
    const res = await fetch(`${STARGUARD_BASE}/api/tokidapp/workflows`, {
      headers: { "Accept": "application/json" },
      signal: AbortSignal.timeout(5000),
    })
    if (!res.ok) return []
    const data: any = await res.json()
    return data.workflows || []
  } catch {
    return []
  }
}

async function getWorkflowDefinitions(): Promise<any[]> {
  const now = Date.now()
  if (!workflowDefinitionsCache || now - workflowCacheTime > WORKFLOW_CACHE_TTL) {
    workflowDefinitionsCache = await fetchWorkflowDefinitions()
    workflowCacheTime = now
  }
  return workflowDefinitionsCache
}

// ── Routes ────────────────────────────────────────────────────

export function registerTokidappRoutes(app: FastifyInstance) {
  // Proxy: serve workflow definitions from StarGuard with local cache
  app.get("/api/tokidapp/workflows", async () => {
    const workflows = await getWorkflowDefinitions()
    return { version: 1, updatedAt: new Date().toISOString().split("T")[0], workflows, digitalAssets: [] }
  })

  // Health / status
  app.get("/api/tokidapp/status", async () => ({
    status: "ok",
    activeSockets: activeSockets.size,
    workspaceRoot: WORKSPACE_ROOT,
    vercelHookConfigured: !!VERCEL_DEPLOY_HOOK_URL,
  }))

  // Deploy shortcut (HTTP POST, no WebSocket needed)
  const DeployBodySchema = z.object({
    commitMsg: z.string().min(1),
  })

  app.post("/api/tokidapp/deploy", async (request, reply) => {
    try {
      const body = DeployBodySchema.parse(request.body ?? {})
      const send = (msg: string) => {} // no-op for HTTP path
      const gitResult = await gitCommitPush(body.commitMsg, send)
      const deployResult = await triggerVercelDeploy(send)
      return { git: gitResult, deploy: deployResult }
    } catch (error) {
      request.log.error({ err: error }, "TokiDAPP deploy failed")
      reply.code(500)
      return { error: (error as Error).message }
    }
  })

  // WS session info
  const SessionQuerySchema = z.object({
    token: z.string().min(1),
  })

  app.get("/api/tokidapp/ws/info", async (request, reply) => {
    try {
      const query = SessionQuerySchema.parse(request.query)
      return { sessionId: `tokidapp_${query.token}`, active: activeSockets.has(`tokidapp_${query.token}`) }
    } catch {
      reply.code(400)
      return { error: "token required" }
    }
  })
}

// ── WebSocket Upgrade Handler ────────────────────────────────

export function registerTokidappWebSocket(app: FastifyInstance) {
  app.server.on("upgrade", (request, socket, head) => {
    // Only handle /api/tokidapp/ws paths
    const rawUrl = request.url ?? "/"
    let parsed: URL
    try {
      parsed = new URL(rawUrl, "http://localhost")
    } catch {
      return
    }

    if (!parsed.pathname.startsWith("/api/tokidapp/ws")) return

    // Validate token
    const token = parsed.searchParams.get("token") || ""
    if (!token) {
      socket.write("HTTP/1.1 401 Unauthorized\r\n\r\n")
      socket.destroy()
      return
    }

    const sessionId = `tokidapp_${token}`
    const socketRef: TokiDAPPWebSocket = {
      send: (msg: string) => {
        try { socket.write(msg + "\n") } catch { /* ignore */ }
      },
      close: (code, reason) => {
        try { socket.destroy() } catch { /* ignore */ }
      },
    }

    // Accept the WebSocket upgrade
    const key = request.headers["sec-websocket-key"] || ""
    const accept = require("crypto").createHash("sha1")
      .update(key + "258EAFA5-E914-47DA-95CA-5AB5-4BDC3B1B1E07")
      .digest("base64")

    socket.write(
      "HTTP/1.1 101 Switching Protocols\r\n" +
      "Upgrade: websocket\r\n" +
      "Connection: Upgrade\r\n" +
      `Sec-WebSocket-Accept: ${accept}\r\n\r\n`,
    )

    activeSockets.set(sessionId, socketRef)

    // Send welcome
    socketRef.send(JSON.stringify({
      type: "message",
      content: "TokiDAPP Concierge connected. I can investigate code, generate features, run tests, deploy to Vercel, spawn agents (OpenCode/OpenCoder/OpenAgent), schedule tasks, and assign work to users.",
    }))

    // Handle incoming data (simple line-delimited JSON)
    let buffer = ""
    socket.on("data", (chunk: Buffer) => {
      buffer += chunk.toString()
      const lines = buffer.split("\n")
      buffer = lines.pop() || ""

      for (const line of lines) {
        const trimmed = line.trim()
        if (!trimmed) continue

        try {
          const msg = JSON.parse(trimmed)

          if (msg.type === "ping") {
            socketRef.send(JSON.stringify({ type: "pong" }))
            continue
          }

          if (msg.type === "cancel") {
            socketRef.send(JSON.stringify({ type: "message", content: "Cancelled." }))
            continue
          }

          if (msg.type === "message" && msg.content) {
            routeMessage(
              msg.content,
              (outgoing) => socketRef.send(outgoing),
              msg.workflowSlug,
              msg.workflowStep,
            )
            continue
          }

          if (msg.type === "deploy" && msg.commitMsg) {
            ;(async () => {
              const gitResult = await gitCommitPush(msg.commitMsg, (outgoing) => socketRef.send(outgoing))
              socketRef.send(JSON.stringify({ type: "deploy_status", status: "committed", commitMsg: msg.commitMsg, commitHash: gitResult }))

              const deployResult = await triggerVercelDeploy((outgoing) => socketRef.send(outgoing))
              socketRef.send(JSON.stringify({ type: "deploy_status", status: deployResult.includes("failed") ? "failed" : "building", logs: deployResult }))
            })()
            continue
          }
        } catch {
          // Ignore malformed JSON
        }
      }
    })

    socket.on("close", () => {
      activeSockets.delete(sessionId)
    })

    socket.on("error", () => {
      activeSockets.delete(sessionId)
    })
  })
}
