import { execSync } from "child_process"
import * as fs from "fs"
import * as path from "path"
import { rollbackToPreviousCommit } from "../orchestrator/rollback"

// ── Helpers ───────────────────────────────────────────────────

export async function captureGitDiff(workspaceRoot: string): Promise<string> {
  try {
    return execSync("git diff --cached --stat 2>/dev/null || echo '(no changes)'", {
      cwd: workspaceRoot, encoding: "utf-8", maxBuffer: 1024 * 1024,
    })
  } catch { return "(could not capture diff)" }
}

export async function checkDeployStatus(params: {
  vercelToken?: string
  vercelProjectId?: string
  vercelTeamId?: string
}): Promise<string> {
  const { vercelToken, vercelProjectId, vercelTeamId } = params
  if (!vercelToken) return "VERCEL_TOKEN not configured."

  try {
    const searchParams = new URLSearchParams({ limit: "1" })
    if (vercelProjectId) searchParams.set("projectId", vercelProjectId)
    if (vercelTeamId) searchParams.set("teamId", vercelTeamId)

    const res = await fetch(`https://api.vercel.com/v6/deployments?${searchParams}`, {
      headers: { Authorization: `Bearer ${vercelToken}` },
    })

    if (!res.ok) return "Could not fetch deploy status."
    const data: any = await res.json()
    const deploy = data.deployments?.[0]
    if (!deploy) return "No deployments found."

    return [
      `Latest deploy: ${deploy.name}`,
      `URL: https://${deploy.url}`,
      `State: ${deploy.readyState}`,
      `Created: ${new Date(deploy.createdAt).toISOString()}`,
    ].join("\n")
  } catch {
    return "Could not fetch deploy status."
  }
}

// ── Tool Functions ────────────────────────────────────────────

export async function investigateCodebase(
  query: string,
  workspaceRoot: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Searching the codebase..." }))

  const keywords = query.replace(/investigate|find|search|look|show|read|examine/gi, "").trim().split(/\s+/).filter(Boolean)
  if (keywords.length === 0) return "What would you like me to investigate?"

  try {
    const pattern = keywords.join("|")
    let results: string
    try {
      results = execSync(
        `rg -l -i "${pattern}" --type ts --type tsx --type css --glob '!node_modules' --glob '!.next' --glob '!public/codenomad' 2>/dev/null | head -20`,
        { cwd: workspaceRoot, encoding: "utf-8", maxBuffer: 1024 * 1024 },
      )
    } catch {
      results = ""
    }

    const fileList = results.trim().split("\n").filter(Boolean)
    if (fileList.length === 0) return `No files found matching: ${keywords.join(", ")}`

    const previews: string[] = []
    for (const file of fileList.slice(0, 3)) {
      try {
        const content = execSync(`head -30 "${file}"`, { cwd: workspaceRoot, encoding: "utf-8", maxBuffer: 1024 * 1024 })
        previews.push(`📄 ${file}:\n${content}`)
      } catch {
        previews.push(`📄 ${file}: (could not read)`)
      }
    }

    return [
      `Found ${fileList.length} files matching: ${keywords.join(", ")}`,
      "",
      ...fileList.map((f) => `- ${f}`),
      "",
      "--- Previews ---",
      "",
      ...previews,
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

export async function generateFeature(
  prompt: string,
  workspaceRoot: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Generating feature..." }))

  const filesCreated: string[] = []

  try {
    if (/page|route/i.test(prompt)) {
      const match = prompt.match(/(\w+)\s*page/i) || prompt.match(/add\s+(?:a\s+)?(\w+)/i)
      const pageName = match ? match[1].toLowerCase() : "new-feature"
      const dir = path.join(workspaceRoot, "src", "app", pageName)
      fs.mkdirSync(dir, { recursive: true })

      const pageContent = [
        "'use client'",
        "",
        `export default function ${pageName.charAt(0).toUpperCase() + pageName.slice(1)}Page() {`,
        "  return (",
        `    <div className="p-8">`,
        `      <h1 className="text-2xl font-bold text-white">${pageName.charAt(0).toUpperCase() + pageName.slice(1)}</h1>`,
        `      <p className="text-gray-400 mt-2">Generated by TokiDAPP Concierge</p>`,
        "    </div>",
        "  )",
        "}",
        "",
      ].join("\n")

      fs.writeFileSync(path.join(dir, "page.tsx"), pageContent)
      filesCreated.push(`src/app/${pageName}/page.tsx`)
    }

    if (/component/i.test(prompt)) {
      const match = prompt.match(/(\w+)\s*component/i) || prompt.match(/component\s+(\w+)/i)
      const compName = match ? match[1] : "GeneratedComponent"
      const compPascal = compName.charAt(0).toUpperCase() + compName.slice(1)

      const componentContent = [
        "'use client'",
        "",
        `export function ${compPascal}({ className = "" }: { className?: string }) {`,
        "  return (",
        `    <div className={\`p-4 rounded-xl border border-white/10 bg-white/5 \${className}\`}>`,
        `      <p className="text-gray-400">${compPascal}</p>`,
        "    </div>",
        "  )",
        "}",
        "",
      ].join("\n")

      const compDir = path.join(workspaceRoot, "src", "components")
      fs.mkdirSync(compDir, { recursive: true })
      fs.writeFileSync(path.join(compDir, `${compPascal}.tsx`), componentContent)
      filesCreated.push(`src/components/${compPascal}.tsx`)
    }

    if (filesCreated.length === 0) {
      return "Please be more specific. Try: 'Add a metrics page' or 'Create a Dashboard component'"
    }

    return [
      `Created ${filesCreated.length} file(s):`,
      "",
      ...filesCreated.map((f) => `- ${f}`),
      "",
      "Run `bun run type-check` to verify.",
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

export async function runTests(
  workspaceRoot: string,
  send?: (msg: string) => void,
  timeout?: number,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Running tests..." }))

  try {
    const startTime = Date.now()
    let output: string
    try {
      output = execSync("bun run test 2>&1", {
        cwd: workspaceRoot, encoding: "utf-8", maxBuffer: 1024 * 1024, timeout: timeout ?? 120000,
      })
    } catch (e: any) {
      output = e.stdout || e.message || "Test execution failed"
    }

    const duration = ((Date.now() - startTime) / 1000).toFixed(1)
    const passMatch = output.match(/(\d+)\s+passed/i)
    const failMatch = output.match(/(\d+)\s+failed/i)
    const passed = passMatch ? passMatch[1] : "?"
    const failed = failMatch ? failMatch[1] : "0"

    return [
      `Tests completed in ${duration}s`,
      `Passed: ${passed} | Failed: ${failed}`,
      failed !== "0" ? "Some tests failed." : "All tests passing!",
      "",
      "--- Last 20 lines ---",
      output.split("\n").slice(-20).join("\n"),
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

export async function gitStatus(workspaceRoot: string): Promise<string> {
  try {
    const branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd: workspaceRoot, encoding: "utf-8" }).trim()
    const status = execSync("git status --short", { cwd: workspaceRoot, encoding: "utf-8" }).trim()
    const log = execSync("git log --oneline -5", { cwd: workspaceRoot, encoding: "utf-8" }).trim()
    const filesChanged = status ? status.split("\n").length : 0

    return [
      `Branch: ${branch}`,
      `Uncommitted: ${filesChanged} file(s)`,
      status ? `\n${status}` : "\n   (clean)",
      "",
      "--- Recent commits ---",
      log,
    ].join("\n")
  } catch (err) {
    return `Error: ${(err as Error).message}`
  }
}

export async function gitCommitPush(
  commitMsg: string,
  workspaceRoot: string,
  starguardBase: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Committing changes..." }))

  try {
    const diff = await captureGitDiff(workspaceRoot)
    const branch = execSync("git rev-parse --abbrev-ref HEAD", { cwd: workspaceRoot, encoding: "utf-8" }).trim()
    execSync("git add -A", { cwd: workspaceRoot, encoding: "utf-8" })
    execSync(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`, { cwd: workspaceRoot, encoding: "utf-8" })

    if (send) send(JSON.stringify({ type: "stream", delta: "Pushing to remote..." }))
    execSync(`git push origin ${branch}`, { cwd: workspaceRoot, encoding: "utf-8", timeout: 30000 })

    const hash = execSync("git rev-parse HEAD", { cwd: workspaceRoot, encoding: "utf-8" }).trim()

    // Store diff as blob if starguardBase configured
    try {
      await fetch(`${starguardBase}/api/tokidapp/deploy-status`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "store_diff",
          commitHash: hash,
          commitMsg,
          diff,
          branch,
        }),
      })
    } catch { /* non-critical */ }

    return `Committed and pushed: ${hash.slice(0, 7)} on ${branch}\n\nFiles changed:\n${diff}`
  } catch (err) {
    return `Git error: ${(err as Error).message}`
  }
}

export async function triggerVercelDeploy(
  deployHookUrl: string | undefined,
  send?: (msg: string) => void,
): Promise<string> {
  if (!deployHookUrl) {
    return "VERCEL_DEPLOY_HOOK_URL not configured. Set it in the environment."
  }

  if (send) send(JSON.stringify({ type: "stream", delta: "Triggering Vercel deploy..." }))

  try {
    const res = await fetch(deployHookUrl, { method: "POST" })
    if (!res.ok) {
      const err = await res.text()
      return `Deploy hook failed: ${res.status} ${err}`
    }
    return "Deploy triggered on Vercel. Building..."
  } catch (err) {
    return `Deploy error: ${(err as Error).message}`
  }
}

export async function spawnAgent(
  prompt: string,
  starguardBase: string,
  workspaceRoot: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Spawning agent workspace..." }))

  if (!starguardBase) return "StarGuard API not configured."

  // Parse agent type from prompt
  const agentType = prompt.includes("opencoder")
    ? "OPENCODER"
    : prompt.includes("openagent")
      ? "OPENAGENT"
      : prompt.includes("buildmate")
        ? "BUILDMATE"
        : "OPENCODE"

  const match = prompt.match(/in\s+([\w/-]+)/i)
  const workspacePath = match ? path.join(workspaceRoot, match[1]) : workspaceRoot

  try {
    const res = await fetch(`${starguardBase}/api/tokidapp/agents/spawn`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId: `codenomad_${Date.now()}`,
        workspacePath,
        agentType,
        workspaceName: `Agent-${agentType}-${Date.now()}`,
      }),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to spawn agent: ${err}`
    }

    const workspace = await res.json()
    return [
      `✅ **${agentType} agent spawned!**`,
      ``,
      `Workspace ID: \`${workspace.codenomadWorkspaceId || workspace.id}\``,
      workspace.codenomadProxyUrl ? `Proxy URL: ${workspace.codenomadProxyUrl}` : "",
      `Status: ${workspace.status}`,
      ``,
      `The agent is ready. Assign tasks to it using "assign task to <agent>".`,
    ].filter(Boolean).join("\n")
  } catch (err) {
    return `Error spawning agent: ${(err as Error).message}`
  }
}

export async function scheduleTask(
  prompt: string,
  starguardBase: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Creating scheduled task..." }))

  if (!starguardBase) return "StarGuard API not configured."

  // Parse task info from prompt
  const titleMatch = prompt.match(/(?:task|to)\s+[""]?([^""]+?)[""]?\s*(?:for|at|with|$)/i)
  const title = titleMatch ? titleMatch[1].trim() : prompt.replace(/schedule|create|add|task/gi, "").trim()
  const priorityMatch = prompt.match(/priority\s*[:\s]*(\d+)/i)
  const priority = priorityMatch ? parseInt(priorityMatch[1]) : 0

  // Parse scheduled time
  let scheduledFor: string | undefined
  const timeMatch = prompt.match(/(?:at|for)\s+(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})/i) || prompt.match(/(?:at|for)\s+(\d{4}-\d{2}-\d{2})/i)
  if (timeMatch) scheduledFor = timeMatch[1]

  // Parse agent type
  const agentType = prompt.includes("opencoder")
    ? "OPENCODER" : prompt.includes("openagent")
      ? "OPENAGENT" : "OPENCODE"

  // Parse assignee
  const assignMatch = prompt.match(/(?:assign|to|for)\s+user\s+(\S+@\S+)/i)
  const assignedToUserId = assignMatch ? assignMatch[1] : undefined

  try {
    const body: Record<string, unknown> = {
      sessionId: `codenomad_${Date.now()}`,
      title,
      agentType,
      priority,
    }
    if (scheduledFor) body.scheduledFor = scheduledFor
    if (assignedToUserId) body.assignedToUserId = assignedToUserId

    const res = await fetch(`${starguardBase}/api/tokidapp/tasks`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to schedule task: ${err}`
    }

    const task = await res.json()
    return [
      `✅ **Task scheduled!**`,
      ``,
      `Title: ${task.title}`,
      `ID: \`${task.id}\``,
      `Agent: ${task.agentType}`,
      `Priority: ${task.priority}`,
      scheduledFor ? `Scheduled: ${scheduledFor}` : "Status: PENDING (no schedule set)",
      assignedToUserId ? `Assigned to: ${assignedToUserId}` : "",
      ``,
      `Use "list tasks" to see all scheduled tasks.`,
    ].filter(Boolean).join("\n")
  } catch (err) {
    return `Error scheduling task: ${(err as Error).message}`
  }
}

export async function listTasks(
  filter: string,
  starguardBase: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Fetching tasks..." }))

  if (!starguardBase) return "StarGuard API not configured."

  try {
    const params = new URLSearchParams()
    if (filter.includes("pending")) params.set("status", "PENDING")
    else if (filter.includes("assigned")) params.set("status", "ASSIGNED")
    else if (filter.includes("in progress")) params.set("status", "IN_PROGRESS")
    else if (filter.includes("complete")) params.set("status", "COMPLETED")

    const res = await fetch(`${starguardBase}/api/tokidapp/tasks?${params}`, {
      headers: { "Content-Type": "application/json" },
    })

    if (!res.ok) return "Could not fetch tasks."
    const tasks: any[] = await res.json()

    if (tasks.length === 0) return "No tasks found."

    return [
      `📋 **${tasks.length} task(s)**`,
      "",
      ...tasks.map((t, i) =>
        `**${i + 1}. ${t.title}**` +
        `\n   Status: ${t.status} | Agent: ${t.agentType} | Priority: ${t.priority}` +
        (t.assignedToUserId ? `\n   Assigned to: \`${t.assignedToUserId}\`` : "") +
        (t.scheduledFor ? `\n   Scheduled: ${new Date(t.scheduledFor).toISOString()}` : "") +
        (t.resultSummary ? `\n   Result: ${t.resultSummary}` : ""),
      ),
    ].join("\n")
  } catch (err) {
    return `Error listing tasks: ${(err as Error).message}`
  }
}

export async function assignTask(
  prompt: string,
  starguardBase: string,
  send?: (msg: string) => void,
): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Assigning task..." }))

  if (!starguardBase) return "StarGuard API not configured."

  // Parse task ID and assignee
  const taskIdMatch = prompt.match(/task\s+(\S+)/i)
  const userMatch = prompt.match(/(?:to|user)\s+(\S+@\S+|\S+)/i)

  if (!taskIdMatch) return "Please specify a task ID. Example: assign task abc123 to user@example.com"
  if (!userMatch) return "Please specify a user. Example: assign task abc123 to user@example.com"

  const taskId = taskIdMatch[1]
  const assignee = userMatch[1]

  try {
    const res = await fetch(`${starguardBase}/api/tokidapp/tasks/${taskId}/assign`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ assignedToUserId: assignee }),
    })

    if (!res.ok) {
      const err = await res.text()
      return `Failed to assign task: ${err}`
    }

    const task = await res.json()
    return [
      `✅ **Task assigned!**`,
      ``,
      `Task: ${task.title}`,
      `Assigned to: ${assignee}`,
      `Status: ${task.status}`,
    ].join("\n")
  } catch (err) {
    return `Error assigning task: ${(err as Error).message}`
  }
}

export async function rollbackDeploy(send?: (msg: string) => void): Promise<string> {
  if (send) send(JSON.stringify({ type: "stream", delta: "Rolling back to previous commit..." }))

  const result = await rollbackToPreviousCommit(true)
  if (!result.success) {
    return `Rollback error: ${result.error}`
  }

  return [
    `⏪ **Rolled back to:** ${result.previousHash}`,
    `Previous commit: ${result.previousMsg}`,
    "",
    "Redeploy triggered.",
  ].join("\n")
}
